### ISSUE TITLE
missing  #include "TimerInterrupt_Generic_Debug.h" in ESP8266TimerInterrupt_Generic.h

### ISSUE THREAD

**Issue by mikyjazz** [khoih-prog/TimerInterrupt_Generic#9]
missing  #include "TimerInterrupt_Generic_Debug.h" in ESP8266TimerInterrupt_Generic.h

**Comment by khoih-prog** [comment]
Hi @mikyjazz 

Thanks for the info.

It's redundant and not necessary, and won't create any compile error because of

https://github.com/khoih-prog/TimerInterrupt_Generic/blob/378b3c2f025fe4b40949f0da739519ada4489137/src/TimerInterrupt_Generic.h#L56

Anyway, I've just added to `main` for consistency to many more files.
